core/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('core.views',
    url(r'^(?P<page>\w+)/$', 'static', name='static'),
)

djangoshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout, password_reset
admin.autodiscover()

urlpatterns = [
    url(r'^error404/$', 'core.views.error404', name='core_404'),
    url(r'^$', 'core.views.index', name='index'),
    url(r'^items/', include('items.urls', namespace='items')),
    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^register/$', 'users.views.register', {'autologin': settings.LOGIN_AFTER_SIGNUP}, name='register'),
    url(r'^page/', include('core.urls', namespace='static')),
    url(r'^password_reset/$', password_reset, {'template_name': 'users/password_reset.html'}, name='password_reset'),
    url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^odmin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.page_404'

items/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('items.views',
    url(r'catalog/$', 'catalog', name='catalog'),
    url(r'trash/$', 'trash', name='trash'),
    url(r'order/$', 'order', name='order'),
    url(r'like_(?P<id>\d+)/$', 'likes_item', name='likes'),
    url(r'item/(?P<id>\d+)/$', 'item', name='item'),
)

items/models.py
# coding: utf-8
import uuid
from core.models import AbstractClass
from django.db import models
from users.models import User
from imagekit.models import ProcessedImageField, ImageSpecField
from pilkit.processors import ResizeToFill


def get_path_category_pic(instance, filename):
    ext = filename.split('.')[-1]
    filename = '%s.%s' % (uuid.uuid4(), ext)
    return 'category/%s%s%s' % (filename[:1], filename[2:5], filename)


def get_path_items_pic(instance, filename):
    ext = filename.split('.')[-1]
    filename = '%s.%s' % (uuid.uuid4(), ext)
    return 'items/%s%s%s' % (filename[:1], filename[2:5], filename)


def get_path_gallery_pic(instance, filename):
    ext = filename.split('.')[-1]
    filename = '%s.%s' % (uuid.uuid4(), ext)
    return 'gallery/%s%s%s' % (filename[:1], filename[2:5], filename)


class Category(AbstractClass):
    img = ProcessedImageField(
        upload_to=get_path_category_pic,
        format='PNG',
        options={'quality': 75},
        blank=True,
        null=True
    )
    preview = ImageSpecField(
        source='img',
        processors=[ResizeToFill(300, 300)],
        format='PNG',
        options={'quality': 60}
    )
    title = models.CharField(
        'Заголовок',
        max_length=255,
        null=False,
        blank=False
    )
    descriptions = models.TextField(
        'Описание'
    )

    class Meta:
        verbose_name = u'Категории'
        verbose_name_plural = u'категории'

    def __unicode__(self):
        return self.title


class Gallery(AbstractClass):
    img = ProcessedImageField(
        upload_to=get_path_gallery_pic,
        format='PNG',
        options={'quality': 80},
        blank=True,
        null=True
    )
    preview = ImageSpecField(
        source='img',
        processors=[ResizeToFill(100, 100)],
        format='PNG',
        options={'quality': 40}
    )
    thumbnail = ImageSpecField(
        source='img',
        processors=[ResizeToFill(600, 600)],
        format='PNG',
        options={'quality': 60}
    )
    descriptions = models.CharField(
        'Описание',
        max_length=255,
        blank=False,
        null=False
    )

    class Meta:
        verbose_name = u'Галерея'
        verbose_name_plural = u'галерея'

    def __unicode__(self):
        return self.descriptions


class Color(AbstractClass):
    name = models.CharField(
        'Цвет',
        max_length=255
    )
    hex = models.CharField(
        'hex цвета',
        max_length=6
    )

    class Meta:
        verbose_name = u'Цвет'
        verbose_name_plural = u'цвет'

    def __unicode__(self):
        return self.name


class Sizes(AbstractClass):
    number = models.SmallIntegerField(
        'Размеры',
        default=0,
        blank=False,
        null=False
    )

    class Meta:
        verbose_name = u'Размеры'
        verbose_name_plural = u'размеры'

    def __unicode__(self):
        return '%s' % self.number


class Items(AbstractClass):
    title = models.CharField(
        'Наименование',
        max_length=255
    )
    img = ProcessedImageField(
        upload_to=get_path_items_pic,
        format='PNG',
        options={'quality': 100},
        blank=True,
        null=True
    )
    preview = ImageSpecField(
        source='img',
        processors=[ResizeToFill(300, 300)],
        format='PNG',
        options={'quality': 80}
    )
    visitors = models.IntegerField(
        'Просмотры',
        default=0,
        blank=True,
        null=True,
    )
    likes = models.ManyToManyField(
        User,
        related_name='likes_user',
        blank=True,
    )
    weight = models.DecimalField(
        'Вес',
        max_digits=5,
        decimal_places=2
        # max_value = 999.99
    )
    probe = models.SmallIntegerField(
        'Проба',
        default=0,
        null=True,
        blank=True
    )
    price = models.IntegerField(
        'Цена'
    )
    price_per_gramm = models.SmallIntegerField(
        'Цена за грамм',
        default=0,
        null=True,
        blank=True
    )
    descriptions = models.TextField(
        'Описание'
    )
    gallery = models.ManyToManyField(
        Gallery,
        related_name='gallery_items',
    )
    balance = models.SmallIntegerField(
        'Остаток',
        default=0,
        null=False,
        blank=False
    )
    counter_buy = models.IntegerField(
        'Количество покупок'
    )
    dimensions = models.CharField(
        'Габариты',
        max_length=64,
    )
    material = models.CharField(
        'Материал',
        max_length=64
    )
    color = models.ManyToManyField(
        Color,
        related_name='color_items',
    )
    sizes = models.ManyToManyField(
        Sizes,
        related_name='size_items',
        blank=True,
    )
    categories = models.ForeignKey(
        Category,
        related_name='category_items',
    )

    class Meta:
        verbose_name = u'Товары'
        verbose_name_plural = u'товары'

    def __unicode__(self):
        return self.title

    def get_color(self):
        return '#%s' % self.color


class Trash(AbstractClass):
    article = models.ForeignKey(
        Items,
        related_name='article_trash'
    )
    color = models.ForeignKey(
        Color,
        related_name='color_trash'
    )
    sizes = models.ForeignKey(
        Sizes,
        related_name='sizes_trash'
    )
    count = models.SmallIntegerField(
        'Количество товара',
        default=0,
        null=False,
        blank=False
    )
    user = models.ForeignKey(
        User,
        related_name='trash_user'
    )
    number = models.IntegerField(
        'Номер заказа'
    )

    class Meta:
        verbose_name = u'Корзина'
        verbose_name_plural = u'корзина'

    def __unicode__(self):
        return '%s - %s' % (self.article.title, self.number)


class Travel(AbstractClass):
    name = models.CharField(
        'Способ доставки',
        max_length=32
    )

    class Meta:
        verbose_name = u'Способы доставки'
        verbose_name_plural = u'способы доставки'

    def __unicode__(self):
        return self.name


class Payment(AbstractClass):
    name = models.CharField(
        'Способ оплаты',
        max_length=64
    )

    class Meta:
        verbose_name = u'Способы оплаты'
        verbose_name_plural = u'способы оплаты'

    def __unicode__(self):
        return self.name


class Order(AbstractClass):
    number = models.ForeignKey(
        Trash,
        related_name='number_order'
    )
    various = models.ForeignKey(
        Payment,
        related_name='payment_order'
    )
    user = models.ForeignKey(
        User,
        related_name='order_user'
    )
    date_expiries = models.DateField(
        'Дата доставки',
    )
    address = models.CharField(
        'Адрес доставки',
        max_length=255,
        blank=False,
        null=False
    )
    index = models.ForeignKey(
        User,
        related_name='index_order'
    )
    telephone = models.CharField(
        'Телефон',
        max_length=16,
    )
    status = models.ForeignKey(
        Travel,
        related_name='travel_order'
    )

    class Meta:
        verbose_name = u'Заказы'
        verbose_name_plural = u'заказы'

    def __unicode__(self):
        return '%s - %s (%s)' % (self.number.article, self.status.name, self.various.name)

items/forms.py
from django import forms
from items.models import Order, Trash


class CreateTrash(forms.ModelForm):
    class Meta:
        model = Trash
        fields = ('count', 'number',)
        # number - may be not need TODO


class CreateOrder(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('address', 'index', 'telephone',)

items/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from items.models import Items, Category, Trash, Order
from users.models import User
from items.forms import CreateOrder, CreateTrash


def item(request, id):
    item = get_object_or_404(Items, id=id)
    context = {
        'item': item,
    }
    return render(request, 'items/items.html', context)


def catalog(request):
    context = {
        'category': Category.objects.all(),
        'items': Items.objects.order_by('id'),
    }
    return render(request, 'items/catalog.html', context)


def trash(request):
    context = {
        'form': CreateTrash(request.POST or None),
        'trash': Trash.objects.filter(user=request.user.id).order_by('-id'),
    }
    return render(request, 'items/trash.html', context)


def order(request):
    context = {
        'form': CreateOrder(request.POST or None)
    }
    return render(request, 'items/order.html', context)


def likes_item(request, id):
    item = get_object_or_404(Items, id=id)
    user = User.objects.get(id=request.user.id)
    if user in item.likes.all():
        item.likes.add(user)
        messages.success(request, 'Товар одобрен')
    else:
        item.likes.remove(user)
        messages.error(request, 'Одобрение отвергнуто')
    return HttpResponseRedirect(
        reverse('items:catalog')
    )

templates/items/catalog.html
{% extends 'base.html' %}
{% block title %}Каталог{% endblock %}
{% block base_body %}
Категории, кароч...<br>
{% for foo in category %}
    Наименование: {{ foo.title }}<br>
    <img src="{{ foo.preview.url }}"> <br>
    Описаловка: {{ foo.descriptions }} <hr>
{% endfor %}

Ну и на последок, тавары!!!<br>
    {% if items.count == 0 %}
        <b><h2><i>Пиздец</i></h2>, нихуя нет...</b>
    {% else %}
        {% for item in items %}
            <table border="1px">
                <tr>
                    <td><b>Тайтл</b> - <a href="{% url 'items:item' item.id %}">{{ item.title }}</a></td>
                </tr>
                <tr>
                    <td><b>Превьюха</b><br><img src="{{ item.preview.url }}"></td>
                </tr>
                <tr>
                    <td><b>Лайков</b> - {{ item.likes.count }}</td>
                </tr>
                <tr>
                    <td><b>Баланс</b> - {{ item.balance }}</td>
                </tr>
                <tr>
                    <td><b>Описаловка</b> - {{ item.descriptions }}</td>
                </tr>
            </table>
        {% endfor %}
    {% endif %}

{% endblock %}

templates/items/items.html
{% extends 'base.html' %}
{% block base_body %}

<style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
    .tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
</style>

<table class="tg">
  <tr>
    <th class="tg-031e">Название</th>
    <th class="tg-031e">Превьюха</th>
    <th class="tg-031e">Просмотры</th>
    <th class="tg-031e">Лайки</th>
    <th class="tg-031e">Вес</th>
    <th class="tg-031e">Проба</th>
    <th class="tg-031e">Цена</th>
    <th class="tg-031e">Цена за грамм</th>
    <th class="tg-031e">Описание</th>
    <th class="tg-031e">Галлерея</th>
    <th class="tg-031e">Остаток</th>
    <th class="tg-031e">Количество покупок</th>
    <th class="tg-031e">Габариты</th>
    <th class="tg-031e">Материал</th>
    <th class="tg-031e">Цвет</th>
    <th class="tg-031e">Размер</th>
    <th class="tg-031e">Категория</th>
  </tr>
  <tr>
    <td class="tg-031e">{{ item.title }}</td>
    <td class="tg-031e"><img src="{{ item.preview.url }}"></td>
    <td class="tg-031e">{{ item.visitors }}</td>
    <td class="tg-031e"><a href="{% url 'items:likes' item.id %}">{{ item.likes.count }}</a></td>
    <td class="tg-031e">{{ item.weight }}</td>
    <td class="tg-031e">{{ item.probe }}</td>
    <td class="tg-031e">{{ item.price }}</td>
    <td class="tg-031e">{{ item.price_per_gramm }}</td>
    <td class="tg-031e">{{ item.descriptions | truncatechars:180 }}</td>
    <td class="tg-031e">{% for image in item.gallery.all %}
                            <center>{{ image.descriptions }}</center>
                            <img src="{{ image.preview.url }}">
                        {% endfor %}
    </td>
    <td class="tg-031e">{{ item.balance }}</td>
    <td class="tg-031e">{{ item.counter_buy }}</td>
    <td class="tg-031e">{{ item.dimensions }}</td>
    <td class="tg-031e">{{ item.material }}</td>
    <td class="tg-031e">{% for col in item.color.all %}
                            <span style="color: #{{ col.hex }}">{{ col.name }}</span><hr><br>
                        {% endfor %}
    </td>
    <td class="tg-031e">{% for size in item.sizes.all %}
                            {{ size.number }}<br>
                        {% endfor %}
    </td>
    <td class="tg-031e">{{ item.categories }}</td>
  </tr>
</table>

{% endblock %}

templates/items/trash.html
{% extends 'base.html' %}
{% block title %}Параша{% endblock %}
{% block base_body %}

<style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;}
    .tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
    .tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
</style>

<table class="tg">
  <tr>
    <th class="tg-031e">Наименование</th>
    <th class="tg-031e">Цвет</th>
    <th class="tg-031e">Размер</th>
    <th class="tg-031e">Количство</th>
    <th class="tg-031e">Юзверь</th>
    <th class="tg-031e">Номер заказа</th>
  </tr>
{% for foo in trash %}
  <tr>
    <td class="tg-031e">{{ foo.article }}</td>
    <td class="tg-031e">{{ foo.color }}</td>
    <td class="tg-031e">{{ foo.sizes }}</td>
    <td class="tg-031e">{{ foo.count }}</td>
    <td class="tg-031e">{{ foo.user.get_full_name }}</td>
    <td class="tg-031e">{{ foo.number }}</td>
  </tr>
{% endfor %}
</table>
<hr>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Запилить">
    </form>
{% endblock %}